import type { Case, Evidence, CaseConnection, EvidenceConnection, Tip } from './types'

export const mockCases: Case[] = [
  {
    id: 'case-001',
    codename: 'The Clocktower Signal',
    location: 'North Campus Bell Tower',
    status: 'Investigating',
    lastUpdated: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    position: { x: 120, y: 80 },
    hasHeat: true,
    summary: 'Multiple reports of unusual radio frequency emissions near the bell tower during midnight hours. Campus security found no physical anomalies but electromagnetic readings are elevated.',
    evidenceCount: 10,
    storyText: 'On January 28th, three independent witnesses reported strange humming sounds emanating from the North Campus Bell Tower between 11:45 PM and 12:30 AM. Campus security conducted a sweep but found no physical cause. However, a student radio club member detected anomalous RF signals in the 433 MHz band. Subsequent analysis suggests the signals may be encoded data transmissions.',
  },
  {
    id: 'case-002',
    codename: 'The Vanishing Mural',
    location: 'Arts District - Block 7',
    status: 'Confirmed',
    lastUpdated: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    position: { x: 480, y: 200 },
    hasHeat: false,
    summary: 'A large mural appeared overnight on the Block 7 wall, then vanished completely within 48 hours. Paint analysis shows non-standard compounds.',
    evidenceCount: 8,
    storyText: 'A striking 20-foot mural depicting a wolf silhouette was discovered on the east wall of Block 7 at 6:15 AM on February 2nd. CCTV footage from the area shows a 4-hour gap in recordings. The mural disappeared by February 4th with no residue. Paint chip analysis reveals photoreactive compounds not commercially available.',
  },
  {
    id: 'case-003',
    codename: 'The Fog Machine',
    location: 'Engineering Lab B',
    status: 'Investigating',
    lastUpdated: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    position: { x: 300, y: 420 },
    hasHeat: true,
    summary: 'Unidentified aerosol emissions from a basement vent in Engineering Lab B. Multiple students reported dizziness.',
    evidenceCount: 9,
    storyText: 'Starting February 5th, students in the Engineering Lab B basement reported periodic fog-like emissions from air vent 3B. Building maintenance found no HVAC malfunction. Air quality tests show elevated but non-toxic particulate matter. The emissions occur at roughly 90-minute intervals and last approximately 3 minutes each.',
  },
  {
    id: 'case-004',
    codename: 'The Phantom Ledger',
    location: 'Library Archives - Sub-Level 2',
    status: 'Debunked',
    lastUpdated: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    position: { x: 700, y: 100 },
    hasHeat: false,
    summary: 'Reports of a hidden financial ledger found in the library archives turned out to be a student art project for their thesis on institutional transparency.',
    evidenceCount: 4,
    storyText: 'A tip suggested a hidden financial ledger was discovered in Sub-Level 2 of the university library. Investigation revealed the documents were part of a graduate art installation by student M. Chen, exploring themes of institutional secrecy. The department confirmed the project.',
  },
  {
    id: 'case-005',
    codename: 'The Midnight Whistle',
    location: 'Stadium South Gate',
    status: 'Investigating',
    lastUpdated: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    position: { x: 550, y: 350 },
    hasHeat: true,
    summary: 'A distinct whistle pattern has been heard near the south gate at exactly midnight for seven consecutive nights. Security cameras show no visible source.',
    evidenceCount: 6,
    storyText: 'Since February 1st, campus security and night-shift workers have reported a melodic whistle pattern near Stadium South Gate at precisely 00:00. The pattern repeats three times, each lasting approximately 12 seconds. Directional microphone analysis places the source underground.',
  },
  {
    id: 'case-006',
    codename: 'The Copper Wire Trail',
    location: 'Maintenance Tunnel C',
    status: 'Confirmed',
    lastUpdated: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    position: { x: 180, y: 300 },
    hasHeat: false,
    summary: 'Unauthorized copper wiring discovered running through maintenance tunnels, connecting two buildings. Purpose unknown.',
    evidenceCount: 5,
    storyText: 'During routine maintenance, workers discovered approximately 200 meters of unregistered copper wiring routed through Tunnel C, connecting the Science Building to the Communications Center. The wire appears professionally installed with military-grade insulation.',
  },
  {
    id: 'case-007',
    codename: 'The Glass Eye',
    location: 'Student Union - Room 404',
    status: 'All-clear',
    lastUpdated: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    position: { x: 850, y: 250 },
    hasHeat: false,
    summary: 'Suspicious camera-like device found in Room 404 was identified as an old smoke detector model.',
    evidenceCount: 3,
    storyText: 'A student reported finding what appeared to be a hidden camera in Room 404 of the Student Union. Facilities management identified the device as a discontinued Kidde smoke detector model from 2003, left from a previous renovation.',
  },
  {
    id: 'case-008',
    codename: 'The Echo Chamber',
    location: 'Music Hall Basement',
    status: 'Investigating',
    lastUpdated: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    position: { x: 420, y: 60 },
    hasHeat: false,
    summary: 'Audio recordings captured in the Music Hall basement contain layered voices not present during the recording session.',
    evidenceCount: 7,
    storyText: 'During a late-night recording session, audio engineer T. Reeves captured anomalous audio layers in the Music Hall basement studio. Spectral analysis reveals human voice patterns at frequencies below the audible range. The building sits above a decommissioned civil defense tunnel.',
  },
  {
    id: 'case-009',
    codename: 'The Paper Trail',
    location: 'Admin Building - 3rd Floor',
    status: 'Closed',
    lastUpdated: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    position: { x: 650, y: 450 },
    hasHeat: false,
    summary: 'Missing procurement documents were located in an incorrectly labeled filing cabinet. No foul play suspected.',
    evidenceCount: 2,
    storyText: 'Investigation into missing procurement documents concluded after records were found in a mislabeled cabinet on the 3rd floor. Administrative error confirmed by three independent staff members.',
  },
  {
    id: 'case-010',
    codename: 'The Blank Frequency',
    location: 'Radio Tower - East Ridge',
    status: 'Investigating',
    lastUpdated: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    position: { x: 900, y: 400 },
    hasHeat: true,
    summary: 'The campus radio tower is broadcasting on an unregistered frequency during early morning hours. Content appears to be numeric sequences.',
    evidenceCount: 5,
    storyText: 'Campus radio operators discovered an unauthorized broadcast on 107.3 FM between 3:00 and 4:00 AM. The broadcast contains repeated numeric sequences read by a synthesized voice. FCC records show no licensed operation on this frequency in the area.',
  },
  {
    id: 'case-011',
    codename: 'The Phantom Fire',
    location: 'Science Building - East Wing',
    status: 'Debunked',
    lastUpdated: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    position: { x: 380, y: 500 },
    hasHeat: false,
    summary: 'A student reported a fire in the Science Building, but official records confirm it was a false alarm. A fabricated image circulated on social media claiming to show the fire, revealing a coordinated misinformation campaign.',
    evidenceCount: 3,
    storyText: 'On February 13th at 10:15 PM, a student posted on social media claiming to witness a fire in the Science Building East Wing. Campus Safety responded immediately and found no fire, confirming it as a false alarm at 10:22 PM. However, a fake image purporting to show flames in the building circulated widely on student messaging apps. Forensic analysis revealed the image was digitally manipulated using an older fire photo from a different location. The coordinated timing suggests deliberate misinformation.',
  },
]

export const mockCaseConnections: CaseConnection[] = [
  { fromId: 'case-001', toId: 'case-010' },
  { fromId: 'case-001', toId: 'case-006' },
  { fromId: 'case-003', toId: 'case-005' },
  { fromId: 'case-006', toId: 'case-008' },
]

// Detailed evidence for case-001 (The Clocktower Signal)
export const mockEvidence: Evidence[] = [
  {
    id: 'ev-001', caseId: 'case-001', type: 'text', title: 'Witness Statement - J. Harper',
    authenticity: 'verified', extractedEntities: ['J. Harper', 'Night Security', 'Subject Alpha'],
    extractedLocations: ['Bell Tower', 'North Campus'], keyPoints: ['Heard humming at 11:52 PM', 'Duration approx 8 minutes', 'No visible source identified'],
    source: 'Investigator', timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: ['Corroborates with ev-002'],
    authenticitySignals: ['Source verified via campus ID', 'Statement consistent across two interviews'],
  },
  {
    id: 'ev-002', caseId: 'case-001', type: 'text', title: 'Witness Statement - K. Osei',
    authenticity: 'verified', extractedEntities: ['K. Osei', 'Radio Club'],
    extractedLocations: ['Bell Tower', 'Physics Lab'], keyPoints: ['Detected 433 MHz signal', 'Signal was pulsed, not continuous', 'Recorded 14-second sample'],
    source: 'Public Tip', timestamp: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: [],
    authenticitySignals: ['Verified student radio club member', 'Technical expertise confirmed'],
  },
  {
    id: 'ev-003', caseId: 'case-001', type: 'image', title: 'RF Spectrum Analysis Screenshot',
    contentUrl: '/placeholder-evidence.jpg', authenticity: 'verified',
    extractedEntities: ['RTL-SDR', 'Spectrum Analyzer'], extractedLocations: ['Bell Tower perimeter'],
    keyPoints: ['Clear spike at 433.92 MHz', 'Signal pattern repeats every 90 seconds', 'Bandwidth suggests data modulation'],
    source: 'Investigator', timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: ['Matches K. Osei description'],
    authenticitySignals: ['EXIF data intact', 'Timestamp consistent', 'Device: Samsung Galaxy S23'],
  },
  {
    id: 'ev-004', caseId: 'case-001', type: 'video', title: 'Security Camera Footage - Tower Base',
    contentUrl: '/placeholder-evidence.jpg', authenticity: 'suspicious',
    extractedEntities: ['Camera 7B', 'Unidentified Figure'], extractedLocations: ['Bell Tower entrance', 'North path'],
    keyPoints: ['Figure approaches at 11:48 PM', 'Face not visible', 'Carries metallic object', 'Departs at 12:15 AM'],
    source: 'Investigator', timestamp: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(), reviewed: false, notes: [],
    authenticitySignals: ['Compression artifacts detected', 'Possible frame interpolation at 11:55-11:58 timestamp', 'Resolution inconsistency in lower quadrant'],
    videoExtract: {
      transcript: '[11:48:12] Movement detected at north entrance... [11:48:30] Figure enters frame from east path, carrying elongated metallic object... [11:55:00-11:58:00] Footage quality degrades... [12:15:22] Figure exits frame heading northwest.',
      keyMoments: [
        { time: '11:48:30', description: 'Subject enters frame carrying unknown device' },
        { time: '11:55:00', description: 'Footage quality anomaly begins' },
        { time: '12:15:22', description: 'Subject exits toward maintenance tunnel' },
      ],
      duration: '27:10',
    },
  },
  {
    id: 'ev-005', caseId: 'case-001', type: 'text', title: 'EMF Reading Report',
    authenticity: 'verified', extractedEntities: ['Dr. Fielding', 'EMF Meter'],
    extractedLocations: ['Bell Tower - Level 3', 'Bell Tower - Roof'], keyPoints: ['Elevated EMF at roof level', 'Normal readings below Level 2', 'Peak readings between 11 PM and 1 AM'],
    source: 'Investigator', timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: ['Consistent with RF evidence'],
    authenticitySignals: ['Report from credentialed faculty member', 'Equipment calibration records provided'],
  },
  {
    id: 'ev-006', caseId: 'case-001', type: 'image', title: 'Photo of Antenna Mount on Roof',
    contentUrl: '/placeholder-evidence.jpg', authenticity: 'unknown',
    extractedEntities: ['Antenna', 'Mounting Bracket'], extractedLocations: ['Bell Tower roof - NE corner'],
    keyPoints: ['Non-standard antenna mount', 'Recently installed based on bolt condition', 'No work orders match this installation'],
    source: 'Public Tip', timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(), reviewed: false, notes: [],
    authenticitySignals: ['Metadata missing', 'AI-likeness signals detected (heuristic)', 'No EXIF geolocation data'],
  },
  {
    id: 'ev-007', caseId: 'case-001', type: 'text', title: 'Maintenance Log Review',
    authenticity: 'verified', extractedEntities: ['Facilities Dept', 'Work Order #4471'],
    extractedLocations: ['Bell Tower'], keyPoints: ['No authorized roof access in past 60 days', 'Last maintenance was electrical inspection on Dec 15', 'Roof hatch lock was reported damaged on Jan 20'],
    source: 'Investigator', timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: ['Lock damage correlates with antenna timeline'],
    authenticitySignals: ['Official university records', 'Verified by facilities manager'],
  },
  {
    id: 'ev-008', caseId: 'case-001', type: 'video', title: 'Student Phone Video - Strange Light',
    contentUrl: '/placeholder-evidence.jpg', authenticity: 'suspicious',
    extractedEntities: ['Anonymous Student', 'LED Indicator'], extractedLocations: ['Bell Tower - viewed from quad'],
    keyPoints: ['Blinking light visible on tower at 12:05 AM', 'Pattern appears non-random', 'Duration 4 seconds on, 2 seconds off'],
    source: 'Public Tip', timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(), reviewed: false, notes: [],
    authenticitySignals: ['Heavy compression artifacts', 'Possible digital zoom enhancement', 'Lighting conditions make verification difficult'],
    videoExtract: {
      transcript: '[00:00] Camera shaking, quad visible in foreground... [00:05] "Look, there it is again" - voice off camera... [00:08] Blinking light visible on tower structure... [00:22] Light pattern repeats... [00:35] "I told you, its been doing that all week" - second voice.',
      keyMoments: [
        { time: '00:08', description: 'First visible blink of anomalous light' },
        { time: '00:22', description: 'Pattern repetition confirms non-random behavior' },
      ],
      duration: '00:42',
    },
  },
  {
    id: 'ev-009', caseId: 'case-001', type: 'image', title: 'Decoded Signal Fragment',
    contentUrl: '/placeholder-evidence.jpg', authenticity: 'unknown',
    extractedEntities: ['Binary Sequence', 'Decryption Attempt'], extractedLocations: [],
    keyPoints: ['Partial decode of 433 MHz signal', 'Contains repeating 16-byte header', 'Payload appears encrypted'],
    source: 'Investigator', timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), reviewed: false, notes: [],
    authenticitySignals: ['Provenance unknown', 'Analysis methodology not documented'],
  },
  {
    id: 'ev-010', caseId: 'case-001', type: 'text', title: 'Anonymous Tip - Insider Knowledge',
    authenticity: 'suspicious', extractedEntities: ['Anonymous', 'Research Project Theta'],
    extractedLocations: ['Bell Tower', 'CS Department'], keyPoints: ['Claims tower is used for unauthorized research', 'Mentions "Project Theta"', 'Alleges faculty involvement'],
    source: 'Public Tip', timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), reviewed: false, notes: [],
    authenticitySignals: ['Anonymous submission', 'Claims unverified', 'Specific details suggest possible insider knowledge'],
  },
  // Evidence for case-002 (The Vanishing Mural)
  {
    id: 'ev-011', caseId: 'case-002', type: 'image', title: 'Mural Photo - Full View',
    contentUrl: '/placeholder-evidence.jpg', authenticity: 'verified',
    extractedEntities: ['Wolf Silhouette', 'Block 7'], extractedLocations: ['Arts District', 'Block 7 East Wall'],
    keyPoints: ['20-foot mural, wolf motif', 'Photographed at 6:20 AM Feb 2', 'High detail visible'],
    source: 'Public Tip', timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: ['First documented photo'],
    authenticitySignals: ['EXIF data intact', 'Geolocation matches Block 7'],
  },
  {
    id: 'ev-012', caseId: 'case-002', type: 'video', title: 'CCTV Gap Analysis',
    contentUrl: '/placeholder-evidence.jpg', authenticity: 'verified',
    extractedEntities: ['Camera 12A', 'System Admin'], extractedLocations: ['Block 7 perimeter'],
    keyPoints: ['4-hour recording gap: 1 AM to 5 AM', 'No system errors logged', 'Manual override suspected'],
    source: 'Investigator', timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: [],
    authenticitySignals: ['Official CCTV system logs', 'IT department verified gap'],
    videoExtract: {
      transcript: '[00:58:22] Normal footage, empty street... [00:59:59] Frame freeze... [05:00:01] Recording resumes, mural visible on wall.',
      keyMoments: [
        { time: '00:59:59', description: 'Last frame before recording gap' },
        { time: '05:00:01', description: 'First frame showing completed mural' },
      ],
      duration: '00:12:00',
    },
  },
  {
    id: 'ev-013', caseId: 'case-002', type: 'text', title: 'Paint Analysis Report',
    authenticity: 'verified', extractedEntities: ['Dr. Voss', 'Chemistry Dept'],
    extractedLocations: ['Block 7', 'Chemistry Lab'], keyPoints: ['Photoreactive titanium dioxide compound', 'Not commercially available', 'UV-activated degradation possible'],
    source: 'Investigator', timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: [],
    authenticitySignals: ['Lab report from university chemistry department', 'Peer reviewed methodology'],
  },
  {
    id: 'ev-014', caseId: 'case-002', type: 'image', title: 'Wall After Disappearance',
    contentUrl: '/placeholder-evidence.jpg', authenticity: 'verified',
    extractedEntities: ['Clean Wall'], extractedLocations: ['Block 7 East Wall'],
    keyPoints: ['No paint residue', 'No cleaning marks', 'Surface identical to pre-mural state'],
    source: 'Investigator', timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: [],
    authenticitySignals: ['EXIF data intact', 'Photographer identified'],
  },
  {
    id: 'ev-015', caseId: 'case-002', type: 'text', title: 'Art Department Inquiry',
    authenticity: 'verified', extractedEntities: ['Prof. Nakamura', 'Art Dept'],
    extractedLocations: ['Arts Building'], keyPoints: ['No student projects match', 'No faculty permissions granted', 'Compound is research-grade'],
    source: 'Investigator', timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: [],
    authenticitySignals: ['Official department response'],
  },
  {
    id: 'ev-016', caseId: 'case-002', type: 'image', title: 'Close-up - Paint Texture',
    contentUrl: '/placeholder-evidence.jpg', authenticity: 'verified',
    extractedEntities: ['Paint Sample'], extractedLocations: ['Block 7 East Wall'],
    keyPoints: ['Layered application technique', 'Minimal brush strokes', 'Spray application suspected'],
    source: 'Investigator', timestamp: new Date(Date.now() - 9.5 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: [],
    authenticitySignals: ['Macro photography with reference scale'],
  },
  {
    id: 'ev-017', caseId: 'case-002', type: 'text', title: 'Security Guard Report',
    authenticity: 'verified', extractedEntities: ['Officer Daniels'], extractedLocations: ['Block 7'],
    keyPoints: ['Patrolled area at 12:30 AM, no mural', 'Did not return until 5:30 AM', 'Mural fully present at 5:30'],
    source: 'Investigator', timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: [],
    authenticitySignals: ['Official security report', 'GPS patrol data matches'],
  },
  {
    id: 'ev-018', caseId: 'case-002', type: 'text', title: 'Anonymous Note Found at Scene',
    authenticity: 'suspicious', extractedEntities: ['The Pack'], extractedLocations: ['Block 7 base'],
    keyPoints: ['Handwritten note: "The Pack watches"', 'Found taped to wall base after mural disappeared', 'Paper is aged parchment style'],
    source: 'Investigator', timestamp: new Date(Date.now() - 6.5 * 24 * 60 * 60 * 1000).toISOString(), reviewed: false, notes: [],
    authenticitySignals: ['No fingerprints', 'Paper commercially available'],
  },
  // Evidence for case-003 (The Fog Machine)
  {
    id: 'ev-019', caseId: 'case-003', type: 'text', title: 'Student Health Reports (3)',
    authenticity: 'verified', extractedEntities: ['Health Center', 'Students A, B, C'],
    extractedLocations: ['Engineering Lab B', 'Health Center'], keyPoints: ['Three students reported dizziness', 'Symptoms lasted 15-30 minutes', 'No long-term effects'],
    source: 'Investigator', timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: [],
    authenticitySignals: ['Official health center records', 'HIPAA-compliant summaries'],
  },
  {
    id: 'ev-020', caseId: 'case-003', type: 'video', title: 'Vent 3B Emission Footage',
    contentUrl: '/placeholder-evidence.jpg', authenticity: 'verified',
    extractedEntities: ['Vent 3B', 'Aerosol Emission'], extractedLocations: ['Engineering Lab B Basement'],
    keyPoints: ['Visible fog from vent', '90-minute emission cycle confirmed', 'Lasts approximately 3 minutes'],
    source: 'Public Tip', timestamp: new Date(Date.now() - 3.5 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: ['Key evidence'],
    authenticitySignals: ['Continuous recording, no cuts', 'Timestamp verified with phone metadata'],
    videoExtract: {
      transcript: '[00:00] Camera positioned facing vent 3B... [01:28:15] First emission begins, visible aerosol... [01:31:22] Emission subsides... [02:58:40] Second emission cycle begins.',
      keyMoments: [
        { time: '01:28:15', description: 'First fog emission captured' },
        { time: '01:31:22', description: 'Emission cycle ends after ~3 minutes' },
        { time: '02:58:40', description: 'Second cycle confirms 90-min interval' },
      ],
      duration: '03:15:00',
    },
  },
  {
    id: 'ev-021', caseId: 'case-003', type: 'text', title: 'Air Quality Test Results',
    authenticity: 'verified', extractedEntities: ['Environmental Safety', 'PM2.5'],
    extractedLocations: ['Engineering Lab B Basement'], keyPoints: ['Elevated PM2.5 during emissions', 'Non-toxic particulate', 'Glycol-based compound detected'],
    source: 'Investigator', timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: [],
    authenticitySignals: ['Certified lab results', 'Chain of custody documented'],
  },
  {
    id: 'ev-022', caseId: 'case-003', type: 'text', title: 'HVAC System Inspection',
    authenticity: 'verified', extractedEntities: ['Facilities Team', 'HVAC Unit 3'],
    extractedLocations: ['Engineering Lab B'], keyPoints: ['No HVAC malfunction found', 'Ductwork clear', 'Source not in main HVAC system'],
    source: 'Investigator', timestamp: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: [],
    authenticitySignals: ['Official inspection report'],
  },
  {
    id: 'ev-023', caseId: 'case-003', type: 'image', title: 'Vent Interior Photo',
    contentUrl: '/placeholder-evidence.jpg', authenticity: 'verified',
    extractedEntities: ['Residue', 'Tubing'], extractedLocations: ['Vent 3B Interior'],
    keyPoints: ['Foreign tubing inside vent', 'Connected to unknown reservoir', 'Installation appears deliberate'],
    source: 'Investigator', timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), reviewed: true, notes: ['Strongest lead'],
    authenticitySignals: ['Photo taken by facilities team', 'Multiple angles available'],
  },
  {
    id: 'ev-024', caseId: 'case-003', type: 'image', title: 'Reservoir Device Photo',
    contentUrl: '/placeholder-evidence.jpg', authenticity: 'verified',
    extractedEntities: ['Timer Circuit', 'Fluid Reservoir'], extractedLocations: ['Vent 3B Plenum Space'],
    keyPoints: ['Battery-powered timer circuit', 'Holds approximately 2 liters of glycol solution', 'Commercial fog machine components modified'],
    source: 'Investigator', timestamp: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(), reviewed: false, notes: [],
    authenticitySignals: ['Chain of custody maintained', 'Evidence tagged and logged'],
  },
  {
    id: 'ev-025', caseId: 'case-003', type: 'text', title: 'Purchase Records Search',
    authenticity: 'unknown', extractedEntities: ['Online Retailer', 'Fog Machine Parts'],
    extractedLocations: [], keyPoints: ['Components available from multiple retailers', 'No campus purchase orders match', 'Estimated cost under $50'],
    source: 'Investigator', timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), reviewed: false, notes: [],
    authenticitySignals: ['Research-based, not direct evidence'],
  },
  {
    id: 'ev-026', caseId: 'case-003', type: 'text', title: 'Building Access Log',
    authenticity: 'verified', extractedEntities: ['Card Reader 3B', 'After-hours Access'],
    extractedLocations: ['Engineering Lab B'], keyPoints: ['7 after-hours access events in past 2 weeks', '3 from unregistered card', 'Card reader logs show 2 AM entries'],
    source: 'Investigator', timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(), reviewed: false, notes: [],
    authenticitySignals: ['Official access control system logs'],
  },
  {
    id: 'ev-027', caseId: 'case-003', type: 'video', title: 'Hallway Camera - Suspicious Entry',
    contentUrl: '/placeholder-evidence.jpg', authenticity: 'verified',
    extractedEntities: ['Hooded Figure', 'Backpack'], extractedLocations: ['Engineering Lab B - Hall 3'],
    keyPoints: ['Person in hoodie enters at 2:14 AM', 'Carrying heavy backpack', 'Exits at 2:47 AM without backpack'],
    source: 'Investigator', timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(), reviewed: false, notes: [],
    authenticitySignals: ['Official CCTV footage', 'No gaps detected'],
    videoExtract: {
      transcript: '[02:14:03] Subject enters hallway 3 from stairwell B... [02:14:15] Subject uses card on reader 3B... [02:47:22] Subject exits, backpack absent.',
      keyMoments: [
        { time: '02:14:03', description: 'Subject enters with heavy backpack' },
        { time: '02:47:22', description: 'Subject exits without backpack' },
      ],
      duration: '00:35:00',
    },
  },
  // Evidence for case-011 (The Phantom Fire)
  {
    id: 'ev-028', caseId: 'case-011', type: 'text', title: 'Social Media Post - Fire Sighting',
    authenticity: 'suspicious',
    extractedEntities: ['@campus_watcher_23', 'Science Building', 'East Wing'],
    extractedLocations: ['Science Building - East Wing', 'Lab 3E'],
    keyPoints: [
      'Posted at 10:15 PM on Feb 13',
      'Claims to see flames from windows',
      'States fire alarm not activated',
      'Account created 2 days prior to post'
    ],
    source: 'Public Tip',
    timestamp: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
    reviewed: true,
    notes: ['New account, suspicious timing'],
    authenticitySignals: [
      'Account age: 2 days (suspicious for emergency report)',
      'No corroborating witnesses',
      'Posted before any fire alarm or official response',
      'Geolocation metadata missing from post'
    ],
  },
  {
    id: 'ev-029', caseId: 'case-011', type: 'text', title: 'Campus Safety Incident Report #2847',
    authenticity: 'verified',
    extractedEntities: ['Officer Martinez', 'Campus Safety', 'Incident #2847'],
    extractedLocations: ['Science Building - East Wing', 'All floors'],
    keyPoints: [
      'Responded to social media report at 10:18 PM',
      'Full building sweep completed by 10:22 PM',
      'No fire, smoke, or elevated temperatures detected',
      'Fire suppression system shows no activation',
      'Confirmed false alarm in official log'
    ],
    source: 'Investigator',
    timestamp: new Date(Date.now() - 24.5 * 60 * 60 * 1000).toISOString(),
    reviewed: true,
    notes: ['Official response record', 'Contradicts social media claim'],
    authenticitySignals: [
      'Official Campus Safety incident report',
      'Officer badge verified: Martinez #4219',
      'Report filed in official emergency system',
      'Building sensors data confirms no fire event',
      'Timestamp matches dispatch log'
    ],
  },
  {
    id: 'ev-030', caseId: 'case-011', type: 'image', title: 'Alleged Fire Photo from Science Building',
    contentUrl: '/placeholder-evidence.jpg',
    authenticity: 'suspicious',
    extractedEntities: ['Image Manipulation', 'Stock Photo', 'Digital Forgery'],
    extractedLocations: ['Science Building (claimed)', 'Unknown (actual)'],
    keyPoints: [
      'Circulated on messaging apps at 10:25 PM (after official all-clear)',
      'Shows flames in building windows',
      'Reverse image search: matches 2019 warehouse fire in Ohio',
      'Image edited to add Science Building signage',
      'EXIF data stripped, preventing origin verification'
    ],
    source: 'Public Tip',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    reviewed: true,
    notes: [
      'Fabricated to support false narrative',
      'Deliberately posted after official denial for confusion'
    ],
    authenticitySignals: [
      'Reverse image match: Ohio warehouse fire (2019)',
      'Metadata analysis: EXIF data intentionally removed',
      'Forensic analysis: Digital cloning detected around signage',
      'Lighting inconsistencies with Feb 13 weather conditions',
      'Posted anonymously from burner account'
    ],
  },
]

export const mockEvidenceConnections: EvidenceConnection[] = [
  // Case 001 connections
  { fromId: 'ev-001', toId: 'ev-002', relation: 'supports' },
  { fromId: 'ev-002', toId: 'ev-003', relation: 'supports' },
  { fromId: 'ev-003', toId: 'ev-005', relation: 'supports' },
  { fromId: 'ev-004', toId: 'ev-001', relation: 'related' },
  { fromId: 'ev-006', toId: 'ev-007', relation: 'supports' },
  { fromId: 'ev-008', toId: 'ev-006', relation: 'related' },
  { fromId: 'ev-009', toId: 'ev-002', relation: 'supports' },
  { fromId: 'ev-010', toId: 'ev-006', relation: 'related' },
  { fromId: 'ev-004', toId: 'ev-008', relation: 'contradicts' },
  // Case 002 connections
  { fromId: 'ev-011', toId: 'ev-014', relation: 'contradicts' },
  { fromId: 'ev-012', toId: 'ev-017', relation: 'supports' },
  { fromId: 'ev-013', toId: 'ev-015', relation: 'supports' },
  { fromId: 'ev-016', toId: 'ev-013', relation: 'related' },
  { fromId: 'ev-018', toId: 'ev-011', relation: 'related' },
  // Case 003 connections
  { fromId: 'ev-019', toId: 'ev-020', relation: 'supports' },
  { fromId: 'ev-020', toId: 'ev-021', relation: 'supports' },
  { fromId: 'ev-022', toId: 'ev-023', relation: 'supports' },
  { fromId: 'ev-023', toId: 'ev-024', relation: 'supports' },
  { fromId: 'ev-026', toId: 'ev-027', relation: 'supports' },
  { fromId: 'ev-024', toId: 'ev-025', relation: 'related' },
  // Case 011 connections - Fire misinformation inference
  { fromId: 'ev-029', toId: 'ev-028', relation: 'contradicts' }, // Official report contradicts student claim
  { fromId: 'ev-030', toId: 'ev-028', relation: 'supports' },     // Fake image supports false student claim
  { fromId: 'ev-029', toId: 'ev-030', relation: 'contradicts' }, // Official report contradicts fake image
]

export const mockTips: Tip[] = [
  {
    id: 'tip-001', type: 'text', category: 'Suspicious', location: 'West Parking Garage',
    content: 'Saw someone carrying large equipment boxes into the basement access of the west garage at 3 AM last Tuesday.',
    anonymous: true, timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), referenceCode: 'WT-4821',
  },
  {
    id: 'tip-002', type: 'image', category: 'Rumor', location: 'Dining Hall',
    content: 'Found this weird symbol scratched into a table in the back corner of the dining hall.',
    anonymous: false, name: 'Alex Rivera', email: 'a.rivera@university.edu',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), referenceCode: 'WT-4822',
  },
  {
    id: 'tip-003', type: 'video', category: 'Safety', location: 'Science Building Roof',
    content: 'Drone footage showing an open access panel on the science building roof that shouldnt be there.',
    anonymous: true, timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(), referenceCode: 'WT-4823',
  },
  {
    id: 'tip-004', type: 'text', category: 'Scam', location: 'Student Union',
    content: 'Someone is posting fake QR codes on bulletin boards that redirect to a phishing site mimicking the university portal.',
    anonymous: false, name: 'Jordan Kim', timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(), referenceCode: 'WT-4824',
  },
]
